services:
  accounts:
    image: "vikaskumar97/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vikasbank
  loans:
    image: "vikaskumar97/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vikasbank
  cards:
    image: "vikaskumar97/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vikasbank
networks:
 vikasbank:
  driver: bridge